namespace Planetfall.Tests.Walkthrough;

[TestFixture]
public sealed class WalkthroughTestOne : WalkthroughTestBase
{
    [Test]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "A massive explosion rocks the ship")]
    [TestCase("port", null, "Escape Pod")]
    [TestCase("sit", null, "You are now safely cushioned within the web")]
    [TestCase("wait", null, "You feel the pod begin to slide down its ejection")]
    [TestCase("wait", null, "the escape pod tumbles away from th")]
    [TestCase("wait", null, "The auxiliary rockets fire ")]
    [TestCase("wait", null, "The main thrusters fire a long")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "The pod is buffeted")]
    [TestCase("wait", null, "You feel the temperature")]
    [TestCase("wait", null, "The viewport suddenly becomes transparent")]
    [TestCase("wait", null, "The pod is now approaching")]
    [TestCase("wait", null, "The pod lands with a thud")]
    [TestCase("score", null, "would be 3")]
    [TestCase("take kit", null, "Taken")]
    [TestCase("open door", null, "The bulkhead opens and cold ocean")]
    [TestCase("out", null, "Underwater")]
    [TestCase("up", null, "Crag")]
    [TestCase("score", null, "would be 6")]
    [TestCase("up", null, "Balcony")]
    [TestCase("up", null, "Winding Stair")]
    [TestCase("up", null, "Courtyard")]
    [TestCase("N", null, "Plain Hall")]
    [TestCase("NE", null, "Rec Corridor")]
    [TestCase("E", null, "Mess Corridor")]
    [TestCase("E", null, "Dorm Corridor")]
    [TestCase("E", null, "Corridor Junction")]
    [TestCase("S", null, "Mech Corridor North")]
    [TestCase("S", null, "Mech Corridor")]
    [TestCase("S", null, "Mech Corridor South")]
    [TestCase("SW", null, "Tool Room")]
    [TestCase("take magnet", null, "Taken")]
    [TestCase("E", null, "Machine Shop")]
    [TestCase("E", null, "Robot Shop")]
    [TestCase("activate floyd", null, "happens")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Suddenly, the robot comes to life")]
    [TestCase("score", null, "would be 8")]
    [TestCase("NW", null, "Mech Corridor South")]
    [TestCase("N", null, "Mech Corridor")]
    [TestCase("N", null, "Mech Corridor North")]
    [TestCase("N", null, "Corridor Junction")]
    [TestCase("N", null, "Admin Corridor South")]
    [TestCase("put magnet on crevice", null, "clank", "steel key")]
    [TestCase("S", null, "Corridor Junction")]
    [TestCase("W", null, "Dorm Corridor")]
    [TestCase("W", null, "Mess Corridor")]
    [TestCase("unlock padlock with key", null, "springs open")]
    [TestCase("remove lock", null, "Taken")]
    [TestCase("open door", null, "Opened")]
    [TestCase("N", null, "Storage West")]
    [TestCase("score", null, "would be 12")]
    [TestCase("drop all", null, "Dropped")]
    [TestCase("take ladder", null, "Taken")]
    [TestCase("S", null, "Mess")]
    [TestCase("E", null, "Dorm")]
    [TestCase("E", null, "Junction", "Finally, you see an intersection")]
    [TestCase("N", null, "South")]
    [TestCase("N", null, "Admin")]
    [TestCase("drop ladder", null, "Dropped")]
    [TestCase("extend ladder", null, "The ladder extends ")]
    [TestCase("place ladder across rift", null, "The ladder swings out ")]
    [TestCase("N", null, "Admin", "North", "slowly make your way across the swaying")]
    [TestCase("score", null, "would be 16")]
    [TestCase("W", null, "Small Office")]
    [TestCase("open desk", null, "Opening the small")]
    [TestCase("take upper card", null, "Taken")]
    [TestCase("score", null, "would be 17")]
    [TestCase("take kitchen card", null, "Taken")]
    [TestCase("score", null, "would be 18")]
    [TestCase("W", null, "Large Office")]
    [TestCase("open desk", null, "Opening the large desk reveals a shuttle access card")]
    [TestCase("take shuttle card", null, "Taken")]
    [TestCase("score", null, "would be 19")]
    [TestCase("E", null, "Small Office")]
    [TestCase("E", null, "Admin", "North")]
    [TestCase("S", null, "Admin", "slowly make your way across the swaying")]
    [TestCase("S", null, "South")]
    [TestCase("S", null, "Junction")]
    [TestCase("W", null, "Dorm", "Finally, you see an intersection")]
    [TestCase("W", null, "Mess Corridor")]
    [TestCase("S", null, "Mess Hall")]
    [TestCase("take canteen", null, "Taken")]
    [TestCase("slide kitchen access card through slot", null, "slides", "Floyd claps")]
    [TestCase("S", null, "Kitchen")]
    [TestCase("score", null, "would be 23")]
    [TestCase("take lower card", null, "Taken")]
    [TestCase("score", null, "would be 24")]
    [TestCase("N", null, "Mess Hall")]
    [TestCase("N", null, "Mess Corridor")]
    [TestCase("E", null, "Dorm")]
    [TestCase("E", null, "Junction")]
    [TestCase("S", null, "Mech Corridor North")]
    [TestCase("S", null, "Mech Corridor")]
    [TestCase("S", null, "Mech Corridor South")]
    [TestCase("SW", null, "Tool Room")]
    [TestCase("take flask", null, "Taken")]
    [TestCase("E", null, "Machine Shop")]
    [TestCase("put flask under spout", null, "sitting under the spout")]
    [TestCase("press black button", null, "The fluid gradually turns milky white")]
    [TestCase("take flask", null, "Taken")]
    [TestCase("N", null, "Mech Corridor South")]
    [TestCase("N", null, "Mech Corridor")]
    [TestCase("N", null, "Mech Corridor North")]
    [TestCase("N", null, "Corridor Junction")]
    [TestCase("E", null, "Elevator Lobby")]
    [TestCase("press blue button", null, "whirring noise from behind the blue door")]
    [TestCase("press red button", null, "The red door begins vibrating a bit")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "north end of the room slides open")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press up button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Tower Core")]
    [TestCase("score", null, "would be 28")]
    [TestCase("NE", null, "A black colored light")]
    [TestCase("pour fluid into hole", null, "a gray light")]
    [TestCase("SW", null, "Tower Core")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press down button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Elevator Lobby")]
    [TestCase("W", null, "Corridor Junction")]
    [TestCase("S", null, "Mech Corridor North")]
    [TestCase("S", null, "Mech Corridor")]
    [TestCase("S", null, "Mech Corridor South")]
    [TestCase("S", null, "Machine Shop")]
    [TestCase("put flask under spout", null, "sitting under the spout")]
    [TestCase("press gray button", null, "The fluid gradually turns milky white")]
    [TestCase("take flask", null, "Taken")]
    [TestCase("N", null, "Mech Corridor South")]
    [TestCase("N", null, "Mech Corridor")]
    [TestCase("N", null, "Mech Corridor North")]
    [TestCase("N", null, "Corridor Junction")]
    [TestCase("E", null, "Elevator Lobby")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press up button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Tower Core")]
    [TestCase("NE", null, "A gray colored light")]
    [TestCase("pour fluid into hole", null, "message is now being sent")]
    [TestCase("score", null, "would be 34")]
    [TestCase("SW", null, "Tower Core")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press down button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Elevator Lobby")]
    [TestCase("S", null, "Lower Elevator")]
    [TestCase("slide lower access card through slot", null, "A recorded voice chimes")]
    [TestCase("press down button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("N", null, "Waiting Area")]
    [TestCase("E", null, "Kalamontee Platform")]
    [TestCase("score", null, "would be 38")]
    [TestCase("S", null, "Alfie")]
    [TestCase("E", null, "Control", "parallel rails", "vanishing in the distance")]
    [TestCase("slide shuttle access card through slot", "ResetTime", "activated")]
    [TestCase("push lever", null, "now in the upper position")]
    [TestCase("pull lever", null, "now in the central position", "still reads 5")]
    [TestCase("wait", null, "You pass a sign which says")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "The tunnel levels out")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "15")]
    [TestCase("wait", null, "10")]
    [TestCase("wait", null, "5")]
    [TestCase("wait", null, "brightly lit area")]
    [TestCase("pull lever", null, "comes to rest")]
    [TestCase("W", null, "Alfie")]
    [TestCase("N", null, "Lawanda")]
    [TestCase("score", null, "would be 42")]
    [TestCase("E", null, "Escalator")]
    [TestCase("E", null, "Fork")]
    [TestCase("NE", null, "Systems Corridor West")]
    [TestCase("N", null, "Repair Room")]
    [TestCase("floyd, go north", null, "Just a shiny fromitz board")]
    [TestCase("floyd, take board", null, "If you say so")]
    [TestCase("S", null, "Systems Corridor West")]
    [TestCase("E", null, "Systems Corridor")]
    [TestCase("N", null, "Planetary Defense")]
    [TestCase("open panel", null, "swings open")]
    [TestCase("take second", null, "producing an empty socket")]
    [TestCase("put shiny in panel", null, "The warning lights stop flashing")]
    [TestCase("score", null, "would be 48")]
    [TestCase("drop fried", null, "Dropped")]
    [TestCase("S", null, "Systems Corridor")]
    [TestCase("E", null, "Systems Corridor East")]
    [TestCase("N", null, "Course Control")]
    [TestCase("open cube", null, "The lid swings open", "fused")]
    [TestCase("take bedistor", null, "fused to its socket")]
    [TestCase("S", null, "Systems Corridor East")]
    [TestCase("S", null, "Library Lobby")]
    [TestCase("S", null, "Project Corridor East")]  
    [TestCase("E", null, "Main Lab")]
    [TestCase("S", null, "Lab Storage")]  
    [TestCase("open pocket", null, "You discover a teleportation access card")]
    [TestCase("take teleportation", null, "Taken")]
    [TestCase("N", null, "Main Lab")]
    [TestCase("W", null, "Project Corridor East")]  
    [TestCase("N", null, "Library Lobby")]
    [TestCase("E", null, "Booth")]
    [TestCase("slide teleportation card through slot", null, "Then a light flashes \"Redee.\"")]
    [TestCase("press 2", null, "stomach")]
    [TestCase("W", null, "Lobby")]  
    [TestCase("drop upper", null, "Dropped")]  
    [TestCase("drop lower", null, "Dropped")]
    [TestCase("drop shuttle", null, "Dropped")]
    [TestCase("W", null, "Junction")]  
    [TestCase("S", null, "North")]
    [TestCase("E", null, "East")]
    [TestCase("take bedistor", null, "Taken")]
    [TestCase("W", null, "North")]
    [TestCase("S", null, "Mech")]
    [TestCase("S", null, "South")]
    [TestCase("SW", null, "Tool")]
    [TestCase("take pliers", null, "Taken")]
    [TestCase("NE", null, "South")]
    [TestCase("N", null, "Mech")]
    [TestCase("N", null, "North")]
    [TestCase("N", null, "Junction")]  
    [TestCase("E", null, "Lobby")]  
    [TestCase("E", null, "Booth")]  
    [TestCase("slide teleportation card through slot", null, "Then a light flashes \"Redee.\"")]
    [TestCase("press 3", null, "stomach")]
    [TestCase("W", null, "Library Lobby")]
    [TestCase("N", null, "East")]
    [TestCase("N", null, "Course")]
    [TestCase("take fused with pliers", null, "With a tug")]
    [TestCase("put good in cube", null, "light goes on")]
    [TestCase("score", null, "would be 54")]
    public async Task Walkthrough(string input, string? setup, params string[] expectedResponses)
    {
        if (!string.IsNullOrWhiteSpace(setup)) 
            InvokeGodMode(setup);

        await Do(input, expectedResponses);
    }
}