namespace Planetfall.Tests.Walkthrough;

[TestFixture]

public sealed class WalkthroughTestOne : WalkthroughTestBase
{
    [Test]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "A massive explosion rocks the ship")]
    [TestCase("port", null, "Escape Pod")]
    [TestCase("sit", null, "You are now safely cushioned within the web")]
    [TestCase("wait", null, "You feel the pod begin to slide down its ejection")]
    [TestCase("wait", null, "the escape pod tumbles away from th")]
    [TestCase("wait", null, "The auxiliary rockets fire ")]
    [TestCase("wait", null, "The main thrusters fire a long")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "The pod is buffeted")]
    [TestCase("wait", null, "You feel the temperature")]
    [TestCase("wait", null, "The viewport suddenly becomes transparent")]
    [TestCase("wait", null, "The pod is now approaching")]
    [TestCase("wait", null, "The pod lands with a thud")]
    [TestCase("take kit", null, "Taken")]
    [TestCase("open door", null, "The bulkhead opens and cold ocean")]
    [TestCase("out", null, "Underwater")]
    [TestCase("up", null, "Crag")]
    [TestCase("up", null, "Balcony")]
    [TestCase("up", null, "Winding Stair")]
    [TestCase("up", null, "Courtyard")]
    [TestCase("N", null, "Plain Hall")]
    [TestCase("NE", null, "Rec Corridor")]
    [TestCase("E", null, "Mess Corridor")]
    [TestCase("E", null, "Dorm Corridor")]
    [TestCase("E", null, "Corridor Junction")]
    [TestCase("S", null, "Mech Corridor North")]
    [TestCase("S", null, "Mech Corridor")]
    [TestCase("S", null, "Mech Corridor South")]
    [TestCase("SW", null, "Tool Room")]
    [TestCase("take magnet", null, "Taken")]
    [TestCase("NE", null, "Mech Corridor South")]
    [TestCase("N", null, "Mech Corridor")]
    [TestCase("N", null, "Mech Corridor North")]
    [TestCase("N", null, "Corridor Junction")]
    [TestCase("N", null, "Admin Corridor South")]
    [TestCase("put magnet on crevice", null, "clank", "steel key")]
    [TestCase("S", null, "Corridor Junction")]
    [TestCase("W", null, "Dorm Corridor")]
    [TestCase("W", null, "Mess Corridor")]
    [TestCase("unlock padlock with key", null, "springs open")]
    [TestCase("remove lock", null, "Taken")]
    [TestCase("open door", null, "Opened")]
    [TestCase("N", null, "Storage West")]
    [TestCase("drop all", null, "Dropped")]
    [TestCase("take ladder", null, "Taken")]
    [TestCase("S", null, "Mess")]
    [TestCase("E", null, "Dorm")]
    [TestCase("E", null, "Junction", "Finally, you see an intersection")]
    [TestCase("N", null, "South")]
    [TestCase("N", null, "Admin")]
    [TestCase("drop ladder", null, "Dropped")]
    [TestCase("extend ladder", null, "The ladder extends to a length of around eight meters")]
    [TestCase("place ladder across rift", null, "The ladder swings out across the rift and comes to rest on the far edge, spanning the precipice")]
    [TestCase("N", null, "Admin", "North", "slowly make your way across the swaying")]
    [TestCase("W", null, "Small Office")]
    [TestCase("open desk", null, "Opening the small desk reveals a kitchen access card and a upper elevator access card")]
    [TestCase("take upper card", null, "Taken")]
    [TestCase("take kitchen card", null, "Taken")]
    [TestCase("W", null, "Large Office")]
    [TestCase("open desk", null, "Opening the large desk reveals a shuttle access card")]
    [TestCase("take shuttle card", null, "Taken")]
    [TestCase("E", null, "Small Office")]
    [TestCase("E", null, "Admin", "North")]
    [TestCase("S", null, "Admin", "slowly make your way across the swaying")]
    [TestCase("S", null, "South")]
    [TestCase("S", null, "Junction")]
    [TestCase("W", null, "Dorm", "Finally, you see an intersection")]
    [TestCase("W", null, "Mess Corridor")]
    [TestCase("S", null, "Mess Hall")]
    public async Task Walkthrough(string input, string? setup, params string[] expectedResponses)
    {
        if (!string.IsNullOrWhiteSpace(setup))
            InvokeGodMode(setup);

        await Do(input, expectedResponses);
    }
}
