namespace Planetfall.Tests.Walkthrough;

[TestFixture]
public sealed class WalkthroughTestOne : WalkthroughTestBase
{
    [Test]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "A massive explosion rocks the ship")]
    [TestCase("port", null, "Escape Pod")]
    [TestCase("sit", null, "You are now safely cushioned within the web")]
    [TestCase("wait", null, "You feel the pod begin to slide down its ejection")]
    [TestCase("wait", null, "the escape pod tumbles away from th")]
    [TestCase("wait", null, "The auxiliary rockets fire ")]
    [TestCase("wait", null, "The main thrusters fire a long")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "The pod is buffeted")]
    [TestCase("wait", null, "You feel the temperature")]
    [TestCase("wait", null, "The viewport suddenly becomes transparent")]
    [TestCase("wait", null, "The pod is now approaching")]
    [TestCase("wait", null, "The pod lands with a thud")]
    [TestCase("score", null, "would be 3")]
    [TestCase("take kit", null, "Taken")]
    [TestCase("open door", null, "The bulkhead opens and cold ocean")]
    [TestCase("out", null, "Underwater")]
    [TestCase("up", null, "Crag")]
    [TestCase("score", null, "would be 6")]
    [TestCase("up", null, "Balcony")]
    [TestCase("up", null, "Winding Stair")]
    [TestCase("up", null, "Courtyard")]
    [TestCase("N", null, "Plain Hall")]
    [TestCase("NE", null, "Rec Corridor")]
    [TestCase("E", null, "Mess Corridor")]
    [TestCase("E", null, "Dorm Corridor")]
    [TestCase("E", null, "Corridor Junction")]
    [TestCase("S", null, "Mech Corridor North")]
    [TestCase("S", null, "Mech Corridor")]
    [TestCase("S", null, "Mech Corridor South")]
    [TestCase("SW", null, "Tool Room")]
    [TestCase("take magnet", null, "Taken")]
    [TestCase("E", null, "Machine Shop")]
    [TestCase("E", null, "Robot Shop")]
    [TestCase("activate floyd", null, "happens")]
    [TestCase("wait", null, "Time passes")]
    [TestCase("wait", null, "Suddenly, the robot comes to life")]
    [TestCase("score", null, "would be 8")]
    [TestCase("NW", null, "Mech Corridor South")]
    [TestCase("N", null, "Mech Corridor")]
    [TestCase("N", null, "Mech Corridor North")]
    [TestCase("N", null, "Corridor Junction")]
    [TestCase("N", null, "Admin Corridor South")]
    [TestCase("put magnet on crevice", null, "clank", "steel key")]
    [TestCase("S", null, "Corridor Junction")]
    [TestCase("W", null, "Dorm Corridor")]
    [TestCase("W", null, "Mess Corridor")]
    [TestCase("unlock padlock with key", null, "springs open")]
    [TestCase("remove lock", null, "Taken")]
    [TestCase("open door", null, "Opened")]
    [TestCase("N", null, "Storage West")]
    [TestCase("score", null, "would be 12")]
    [TestCase("drop all", null, "Dropped")]
    [TestCase("take ladder", null, "Taken")]
    [TestCase("S", null, "Mess")]
    [TestCase("E", null, "Dorm")]
    [TestCase("E", null, "Junction", "Finally, you see an intersection")]
    [TestCase("N", null, "South")]
    [TestCase("N", null, "Admin")]
    [TestCase("drop ladder", null, "Dropped")]
    [TestCase("extend ladder", null, "The ladder extends ")]
    [TestCase("place ladder across rift", null, "The ladder swings out ")]
    [TestCase("N", null, "Admin", "North", "slowly make your way across the swaying")]
    [TestCase("score", null, "would be 16")]
    [TestCase("W", null, "Small Office")]
    [TestCase("open desk", null, "Opening the small")]
    [TestCase("take upper card", null, "Taken")]
    [TestCase("score", null, "would be 17")]
    [TestCase("take kitchen card", null, "Taken")]
    [TestCase("score", null, "would be 18")]
    [TestCase("W", null, "Large Office")]
    [TestCase("open desk", null, "Opening the large desk reveals a shuttle access card")]
    [TestCase("take shuttle card", null, "Taken")]
    [TestCase("score", null, "would be 19")]
    [TestCase("E", null, "Small Office")]
    [TestCase("E", null, "Admin", "North")]
    [TestCase("S", null, "Admin", "slowly make your way across the swaying")]
    [TestCase("S", null, "South")]
    [TestCase("S", null, "Junction")]
    [TestCase("W", null, "Dorm", "Finally, you see an intersection")]
    [TestCase("W", null, "Mess Corridor")]
    [TestCase("S", null, "Mess Hall")]
    [TestCase("take canteen", null, "Taken")]
    [TestCase("slide kitchen access card through slot", null, "slides", "Floyd claps")]
    [TestCase("S", null, "Kitchen")]
    [TestCase("score", null, "would be 23")]
    [TestCase("take lower card", null, "Taken")]
    [TestCase("score", null, "would be 24")]
    [TestCase("N", null, "Mess Hall")]
    [TestCase("N", null, "Mess Corridor")]
    [TestCase("E", null, "Dorm")]
    [TestCase("E", null, "Junction")]
    [TestCase("S", null, "Mech Corridor North")]
    [TestCase("S", null, "Mech Corridor")]
    [TestCase("S", null, "Mech Corridor South")]
    [TestCase("SW", null, "Tool Room")]
    [TestCase("take flask", null, "Taken")]
    [TestCase("E", null, "Machine Shop")]
    [TestCase("put flask under spout", null, "sitting under the spout")]
    [TestCase("press black button", null, "The fluid gradually turns milky white")]
    [TestCase("take flask", null, "Taken")]
    [TestCase("N", null, "Mech Corridor South")]
    [TestCase("N", null, "Mech Corridor")]
    [TestCase("N", null, "Mech Corridor North")]
    [TestCase("N", null, "Corridor Junction")]
    [TestCase("E", null, "Elevator Lobby")]
    [TestCase("press blue button", null, "whirring noise from behind the blue door")]
    [TestCase("press red button", null, "The red door begins vibrating a bit")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "north end of the room slides open")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press up button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Tower Core")]
    [TestCase("score", null, "would be 28")]
    [TestCase("NE", null, "A black colored light")]
    [TestCase("pour fluid into hole", null, "a gray light")]
    [TestCase("SW", null, "Tower Core")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press down button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Elevator Lobby")]
    [TestCase("W", null, "Corridor Junction")]
    [TestCase("S", null, "Mech Corridor North")]
    [TestCase("S", null, "Mech Corridor")]
    [TestCase("S", null, "Mech Corridor South")]
    [TestCase("S", null, "Machine Shop")]
    [TestCase("put flask under spout", null, "sitting under the spout")]
    [TestCase("press gray button", null, "The fluid gradually turns milky white")]
    [TestCase("take flask", null, "Taken")]
    [TestCase("N", null, "Mech Corridor South")]
    [TestCase("N", null, "Mech Corridor")]
    [TestCase("N", null, "Mech Corridor North")]
    [TestCase("N", null, "Corridor Junction")]
    [TestCase("E", null, "Elevator Lobby")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press up button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Tower Core")]
    [TestCase("NE", null, "A gray colored light")]
    [TestCase("pour fluid into hole", null, "message is now being sent")]
    [TestCase("score", null, "would be 34")]
    [TestCase("SW", null, "Tower Core")]
    [TestCase("N", null, "Upper Elevator")]
    [TestCase("slide upper access card through slot", null, "A recorded voice chimes")]
    [TestCase("press down button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("S", null, "Elevator Lobby")]
    [TestCase("S", null, "Lower Elevator")]
    [TestCase("slide lower access card through slot", null, "A recorded voice chimes")]
    [TestCase("press down button", null, "vertical movement")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "slides open")]
    [TestCase("N", null, "Waiting Area")]
    [TestCase("E", null, "Kalamontee Platform")]
    [TestCase("score", null, "would be 38")]
    [TestCase("S", null, "Alfie")]
    [TestCase("E", null, "Control", "parallel rails", "vanishing in the distance")]
    [TestCase("slide shuttle access card through slot", "ResetTime", "activated")]
    [TestCase("push lever", null, "now in the upper position")]
    [TestCase("pull lever", null, "now in the central position", "still reads 5")]
    [TestCase("wait", null, "You pass a sign which says")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "The tunnel levels out")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "passes")]
    [TestCase("wait", null, "15")]
    [TestCase("wait", null, "10")]
    [TestCase("wait", null, "5")]
    [TestCase("wait", null, "brightly lit area")]
    [TestCase("pull lever", null, "comes to rest")]
    [TestCase("W", null, "Alfie")]
    [TestCase("N", null, "Lawanda")]
    [TestCase("score", null, "would be 42")]
    [TestCase("E", null, "Escalator")]
    [TestCase("E", null, "Fork")]
    [TestCase("NE", null, "Systems Corridor West")]
    [TestCase("N", null, "Repair Room")]
    [TestCase("floyd, go north", null, "Just a shiny fromitz board")]
    [TestCase("floyd, take board", null, "If you say so")]
    [TestCase("S", null, "Systems Corridor West")]
    [TestCase("E", null, "Systems Corridor")]
    [TestCase("N", null, "Planetary Defense")]
    [TestCase("open panel", null, "swings open")]
    [TestCase("take second", null, "producing an empty socket")]
    [TestCase("put shiny in panel", null, "The warning lights stop flashing")]
    [TestCase("score", null, "would be 48")]
    [TestCase("drop fried", null, "Dropped")]
    [TestCase("S", null, "Systems Corridor")]
    [TestCase("E", null, "Systems Corridor East")]
    [TestCase("N", null, "Course Control")]
    [TestCase("open cube", null, "The lid swings open", "fused")]
    [TestCase("take bedistor", null, "fused to its socket")]
    [TestCase("S", null, "Systems Corridor East")]
    [TestCase("S", null, "Library Lobby")]
    [TestCase("S", null, "Project Corridor East")]  
    [TestCase("E", null, "Main Lab")]
    [TestCase("S", null, "Lab Storage")]  
    [TestCase("open pocket", null, "You discover a teleportation access card")]
    [TestCase("take teleportation", null, "Taken")]
    [TestCase("N", null, "Main Lab")]
    [TestCase("W", null, "Project Corridor East")]  
    [TestCase("N", null, "Library Lobby")]
    [TestCase("E", null, "Booth")]
    [TestCase("slide teleportation card through slot", null, "Then a light flashes \"Redee.\"")]
    [TestCase("press 2", null, "stomach")]
    [TestCase("W", null, "Lobby")]  
    [TestCase("drop upper", null, "Dropped")]  
    [TestCase("drop lower", null, "Dropped")]
    [TestCase("drop shuttle", null, "Dropped")]
    [TestCase("W", null, "Junction")]  
    [TestCase("S", null, "North")]
    [TestCase("E", null, "East")]
    [TestCase("take bedistor", null, "Taken")]
    [TestCase("W", null, "North")]
    [TestCase("S", null, "Mech")]
    [TestCase("S", null, "South")]
    [TestCase("SW", null, "Tool")]
    [TestCase("take pliers", null, "Taken")]
    [TestCase("NE", null, "South")]
    [TestCase("N", null, "Mech")]
    [TestCase("N", null, "North")]
    [TestCase("N", null, "Junction")]  
    [TestCase("E", null, "Lobby")]  
    [TestCase("E", null, "Booth")]  
    [TestCase("slide teleportation card through slot", null, "Then a light flashes \"Redee.\"")]
    [TestCase("press 3", null, "stomach")]
    [TestCase("W", null, "Library Lobby")]
    [TestCase("N", null, "East")]
    [TestCase("N", null, "Course")]
    [TestCase("take fused with pliers", null, "With a tug")]
    [TestCase("put good in cube", null, "light goes on")]
    [TestCase("score", null, "would be 54")]
    [TestCase("S", null, "Systems Corridor East")]
    [TestCase("S", null, "Library Lobby")]
    [TestCase("E", null, "Booth")]  
    [TestCase("slide teleportation card through slot", null, "Then a light flashes \"Redee.\"")]
    [TestCase("press 2", null, "stomach")]
    [TestCase("W", null, "Lobby")]  
    [TestCase("W", null, "Junction")]  
    [TestCase("N", null, "Admin")]
    [TestCase("N", null, "Admin")]
    [TestCase("W", null, "This is a large room filled with tables full of strange equipment. The far wall is filled with a number of monitors. Of these, the ones labelled LIIBREREE, REEAKTURZ, LIIF SUPORT, KUMUUNIKAASHUNZ, PLANATEREE DEFENS and PLANATEREE KORS KUNTROOL are green, but the one labelled PRAJEKT KUNTROOL indicates a malfunctioning condition")] 
    [TestCase("E", null, "Admin")]  
    [TestCase("S", null, "Admin")]
    [TestCase("S", null, "Junction")]
    [TestCase("S", null, "North")]
    [TestCase("S", null, "Mech")]
    [TestCase("S", null, "South")]
    [TestCase("SW", null, "Tool Room")]
    [TestCase("take laser", null, "Taken")]
    [TestCase("remove battery", null, "Taken")]
    [TestCase("drop battery", null, "Dropped")]
    [TestCase("NE", null, "South")]
    [TestCase("N", null, "Mech")]
    [TestCase("N", null, "North")]
    [TestCase("N", null, "Junction")]
    [TestCase("E", null, "Lobby")]  
    [TestCase("E", null, "Booth 2")]  
    [TestCase("slide teleportation card through slot", null, "Then a light flashes \"Redee.\"")]
    [TestCase("press 3", null, "stomach")]
    [TestCase("W", null, "Lobby")]  
    [TestCase("S", null, "East")]  
    [TestCase("S", null, "Computer Room", "Computer is broken")]  
    [TestCase("read output", null, "The printout is hundreds of pages long")] 
    [TestCase("N", null, "East")]  
    [TestCase("E", null, "Main Lab")]  
    [TestCase("open biolock door", null, "The door opens")]   
    [TestCase("SE", null, "West")]  
    [TestCase("E", null, "East")]  
    [TestCase("look through window", null, "magnetic-striped card", "Looks dangerous in there")]  
    [TestCase("open door", null, "plunges into the Bio Lab")]  
    [TestCase("close door", null, "ferocious growlings, the sounds of a skirmish")]  
    [TestCase("wait", null, "three fast knocks, followed by the distinctive sound of tearing metal")]  
    [TestCase("open door", null, "The mutations rush toward the open doorway")]  
    [TestCase("close door", null, "Floyd smiles with contentment")]  
    [TestCase("score", null, "would be 56")]
    [TestCase("take miniaturization card", null, "Taken")]  
    [TestCase("score", null, "would be 57")]
    [TestCase("W", null, "West")]  
    [TestCase("open door", null, "The door opens")]  
    [TestCase("W", null, "Main Lab")]  
    [TestCase("S", null, "Lab Storage")]  
    [TestCase("take fresh battery", null, "Taken")]  
    [TestCase("put battery in laser", null, "The battery is now resting in the depression, attached to the laser.")] 
    [TestCase("N", null, "Main Lab")]  
    [TestCase("W", null, "Project Corridor East")]  
    [TestCase("S", null, "Computer Room")]  
    [TestCase("S", null, "Miniaturization Booth")]  
    [TestCase("slide mini card through slot", null, "A melodic high-pitched voice says \"Miniaturization and teleportation booth activated. Please type in damaged sector number.\"")]
    [TestCase("type 384", null, "followed by a momentary queasiness", "Station 384")]  
    [TestCase("E", null, "Strip Near Station")]  
    [TestCase("score", null, "would be 61")]
    [TestCase("N", null, "Middle of Strip")]
    [TestCase("N", null, "Strip Near Relay")]
    [TestCase("set laser to 1", null, "The dial is now set to 1.")]
    [TestCase("shoot speck with laser", null, "The speck is hit by the beam! It sizzles a little, but isn't destroyed yet.")]
    [TestCase("score", null, "would be 63")]
    [TestCase("shoot speck with laser", null, "The beam hits the speck again! This time, it vaporizes into a fine cloud of ash. The relay slowly begins to close, and a voice whispers in your ear \"Sector 384 will activate in 200 millichrons. Proceed to exit station")]
    [TestCase("score", null, "would be 71")]
    [TestCase("S", null, "Middle of Strip")]
    [TestCase("S", null, "Strip Near Station")]  
    [TestCase("W", null, "switching to Auxiliary Booth", "wrenching of your innards", "only as a receiving station")]  
    [TestCase("score", null, "would be 75")]
    [TestCase("N", null, "Lab Office")]
    [TestCase("examine desk", null, "a memo of some sort")]
    [TestCase("read memo", null, "Propur preecawshunz shud bee taakin")]
    [TestCase("open desk", null, "Opening the desk reveals a gas mask")]
    [TestCase("take mask", null, "Taken")]
    [TestCase("wear gas mask", null, "You are wearing the gas mask")]
    [TestCase("press red button", null, "hissing from beyond the door")]
    [TestCase("open door", null, "The office door is now open.", "filled with a light mist")]
    [TestCase("w", null, "stunned and confused, but are slowly recovering")]
    public async Task Walkthrough(string input, string? setup, params string[] expectedResponses)
    {
        if (!string.IsNullOrWhiteSpace(setup)) 
            InvokeGodMode(setup);

        await Do(input, expectedResponses);
    }
}